apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: database-persistant-volume-claim
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgpassword
              key: PGPASSWORD
        volumeMounts:
                # Identical with volumename defined in volumes under spec
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          # Subpath means pod data will be stored in postgres folder inside persistant volume.
          subPath: postgres

